(add-hook 'Buffer-menu-mode-hook 'rush-buffer-menu-hook)
(add-hook 'ibuffer-mode-hook 'rush-ibuffer-hook)
(add-hook 'dired-mode-hook 'rush-dired-hook)
(add-hook 'bookmark-bmenu-mode-hook 'rush-bmenu-hook)
(eval-after-load 'magit
  '(if (featurep 'magit-utils)
    (require 'rush-nextmagit)
    (add-hook 'magit-status-mode-hook 'rush-magit-status-hook)
    (add-hook 'magit-log-mode-hook 'rush-magit-log-hook)
    (add-hook 'magit-commit-mode-hook 'rush-magit-commit-hook)
    (add-hook 'magit-diff-mode-hook 'rush-magit-diff-hook)
    (add-hook 'magit-branch-manager-mode-hook 'rush-magit-branch-manager-hook)))
(add-hook 'emacs-lisp-mode-hook 'nlinum-mode)
(add-hook 'LaTeX-mode-hook 'rush-latex-hook)
(add-hook 'latex-mode-hook 'rush-latex-hook)
(add-hook 'latex-mode-hook 'nlinum-mode)
(add-hook 'LaTeX-mode-hook 'nlinum-mode)
(add-hook 'lua-mode-hook #'rush-lua-mode-company-init)
(add-hook 'term-mode-hook #'eterm-256color-mode)
(provide 'hooks)
