(add-hook 'Buffer-menu-mode-hook 'rush-buffer-menu-hook)
(add-hook 'ibuffer-mode-hook 'rush-ibuffer-hook)
(add-hook 'dired-mode-hook 'rush-dired-hook)
(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
(add-hook 'bookmark-bmenu-mode-hook 'rush-bmenu-hook)
(eval-after-load 'magit
  '(if (featurep 'magit-utils)
    (require 'rush-nextmagit)
    (add-hook 'magit-status-mode-hook 'rush-magit-status-hook)
    (add-hook 'magit-log-mode-hook 'rush-magit-log-hook)
    (add-hook 'magit-commit-mode-hook 'rush-magit-commit-hook)
    (add-hook 'magit-diff-mode-hook 'rush-magit-diff-hook)
    (add-hook 'magit-branch-manager-mode-hook 'rush-magit-branch-manager-hook)))
(add-hook 'emacs-lisp-mode-hook 'display-line-numbers-mode)
(add-hook 'emacs-lisp-mode-hook 'git-gutter-mode)
(add-hook 'LaTeX-mode-hook 'rush-latex-hook)
(add-hook 'latex-mode-hook 'rush-latex-hook)
(add-hook 'latex-mode-hook 'nlinum-mode)
(add-hook 'LaTeX-mode-hook 'nlinum-mode)
(add-hook 'lua-mode-hook #'rush-lua-mode-company-init)
(add-hook 'term-mode-hook #'eterm-256color-mode)
(add-hook 'python-mode-hook 'anaconda-mode)
(add-hook 'python-mode-hook 'anaconda-eldoc-mode)
;; (add-hook 'python-mode-hook 'jedi:setup)
(defun my/python-mode-hook ()
  (add-to-list 'company-backends 'company-jedi))
(add-hook 'python-mode-hook 'my/python-mode-hook)
(add-hook 'company-mode 'company-quickhelp-mode)
(provide 'hooks)
